### ISSUE TITLE
Employer Can Create Account

### ISSUE THREAD

**Issue by NicoleKMarino** [NicoleKMarino/the_pivot#17]

**Comment by deborahleehamel** [comment]
As an unregistered employer
When I visit the homepage "/"
I expect to see a link to login in the navbar
When I click this link I am redirected to /login 
I expect to see a link on this page titled "Create Account"
When I click this link I am prompted with a form for my account information
and I fill out username
and I fill out password
and I fill out email address
and I fill out company description
And I click "Create Account"
I expect to be redirected to employer dashboard and only see message that approval is pending.
if I leave out any of these fields
it should alert me that account was not successfully created

(After approval from Platform admin)
I should see "Add a job" in nav bar
