### ISSUE TITLE
Guest User can Create an account

### ISSUE THREAD

**Issue by NicoleKMarino** [NicoleKMarino/the_pivot#18]

**Comment by NicoleKMarino** [comment]
As a guest
when I visit /login
and I click the link "Create Account"
I should be redirected to a form 
And I fill out username
And I fill out password
And I fill out email address
And I don't check the box "Are you an employer?"
And click "Create Account"
I should see a message "Your account was successfully created"
And if I click the link "Add Resume to your account"
I should be redirected to dashboard_path
And If I fill out education
And I fill out experience
And click the button "Update my info"
I should see a message "Your resume was successfully updated"

**Comment by deborahleehamel** [comment]
require "rails_helper"

RSpec.describe "Guest can create a user account" do
  context "with valid attributes" do
    it "can create a new user" do
      visit new_user_path
      fill_in "Username", with: "dbhamel"
      fill_in "Email", with: "deborahleehamel@gmail.com"
      fill_in "Address", with: "310 Blake Street"
      fill_in "City", with: "Denver"
      fill_in "State", with: "CO"
      fill_in "Zipcode", with: 80123
      fill_in "user[password]", with: "password"
      fill_in "Password confirmation", with: "password"
      click_link_or_button "Create Account"

```
  expect(current_path).to eq '/dashboard'

  expect(page).to have_content("Your account was successfully created!")
  expect(page).to have_content("Deb Hamel")

end


it "cannot be created without email" do
  visit new_user_path

  fill_in "Username", with: "dbhamel"
  fill_in "Email", with: ""
  fill_in "Address", with: "310 Blake Street"
  fill_in "City", with: "Denver"
  fill_in "State", with: "CO"
  fill_in "Zipcode", with: 80123
  fill_in "user[password]", with: "password"
  fill_in "Password confirmation", with: "password"
  click_link_or_button "Create Account"

  expect(page).to have_content("Missing email - required to create an account")
end

it "will not create account if email taken" do

  visit new_user_path

  fill_in "Username", with: "dbhamel"
  fill_in "Email", with: "deborahleehamel@gmail.com"
  fill_in "Address", with: "310 Blake Street"
  fill_in "City", with: "Denver"
  fill_in "State", with: "CO"
  fill_in "Zipcode", with: 80123
  fill_in "user[password]", with: "password"
  fill_in "Password confirmation", with: "password"
  click_link_or_button "Create Account"


  visit new_user_path

  fill_in "Username", with: "ihamel"
  fill_in "Email", with: "deborahleehamel@gmail.com"
  fill_in "Address", with: "400 Blake Street"
  fill_in "City", with: "Arvada"
  fill_in "State", with: "CO"
  fill_in "Zipcode", with: 80215
  fill_in "user[password]", with: "password2"
  fill_in "Password confirmation", with: "password2"
  click_link_or_button "Create Account"

  expect(page).to have_content("Email has already been taken")
end
```

  end
end

**Comment by roscalabrin** [comment]
The lines bellow should be taken care in the test (sad path)
it should redirect me to my user dashboard
if I leave out any of these fields
it should alert me that account was not successfully created
