### ISSUE TITLE
Platform Admin Can Take Employer Online

### ISSUE THREAD

**Issue by roscalabrin** [NicoleKMarino/the_pivot#27]
Background:  platform admin is logged in

As a platform admin
When I visit "/companies"
And I click the link "Edit Employer Status"
I should be redirected to "/:employer"
And I should see the text "Status: Offline"
If I click the button "Offline"
a flash message should say I turned company.name offline 
Then  I should see the text "Status: Online"

**Comment by roscalabrin** [comment]
do we need to add that the company will be available in the registered user/guest user views or we would cover that on the tests?

**Comment by Laner12** [comment]
I would imagine it will be covered  in the tests

**Comment by deborahleehamel** [comment]
Should a change in employer status trigger an email to be sent to the employer. Maybe something extra to do, if time.
