### ISSUE TITLE
Platform Admin Approves Employer

### ISSUE THREAD

**Issue by roscalabrin** [NicoleKMarino/the_pivot#29]
Background:  platform admin is logged in

As a platform admin
When I visit "/platform-admin/dashboard"
And I click the link "Pending Requests"
I should be redirected to "/platform-admin/requests"
And I should see a list of with the employers' names
If I click on the employer name
I should be redirected to "/:company"
And I should see the title "Pending"
And If I click the button "Approve Request"
I should be redirected to "/:company"
And I should not see the title "Pending"
I should see the text "Request Approved for Company name" 
I should see the text "Status: Online"

**Comment by NicoleKMarino** [comment]
As an employer
when I visit my user dashboard 
and I click "requests pending"
I am redirected to /requests
I am taken to a list 
and if I press "Put Online" 
the company status should change to online

**Comment by roscalabrin** [comment]
Modify user story to allow platform admin to approve request from the  "/platform-admin/requests" (without having to click on the company link)
