### ISSUE TITLE
Registered user can see all Employers

### ISSUE THREAD

**Issue by NicoleKMarino** [NicoleKMarino/the_pivot#4]

**Comment by deborahleehamel** [comment]
As a user
When I visit /employers
I should see content "Explore Companies"
I should see filter drop downs for "location" and "industry"
I should see all listings for all companies/employers

I should see photo of each company
I should see name of each company
I should see location for each company

if I click on photo, company name, location or industry I go to "employer show page"

The path should be "name-of-website/employers/employer-name"
