### ISSUE TITLE
Employer can Edit Job Posting

### ISSUE THREAD

**Issue by NicoleKMarino** [NicoleKMarino/the_pivot#8]

**Comment by deborahleehamel** [comment]
as a employer

when I visit /dashboard
and I click "Manage Jobs"
I should see all jobs
if I click on "Edit"
I should be redirected to an update  form 
I should see current/old information in each field
I should have to enter my password to make any changes
Enter new/changed info in field
then I click submit
I should be redirected to new updated job show page for updated job 
Verify all edited info is changed
Old info should be gone
